### ISSUE TITLE
easy ssh key command

### ISSUE THREAD

**Issue by tolleburker** [GeekVisit/Simple-Skybell-Sniffer#1]
ssh-keygen -t rsa # ENTER to every field
ssh-copy-id username@router-ip

**Comment by allmoney** [comment]
I have router Keenetic. How can I use it?

**Comment by tolleburker** [comment]
Ssh to router to make an Ssh key and enter the commands

**Comment by allmoney** [comment]
My router can't support user without password :( Is any way?

**Comment by allmoney** [comment]
![image](https://user-images.githubusercontent.com/939594/80918826-8fb34c00-8d6f-11ea-9e9d-88ab86a88323.png)

**Comment by tolleburker** [comment]
Which fw version?

**Comment by allmoney** [comment]
> Which fw version?

On screenshot no this information? How can I check fw?

**Comment by tolleburker** [comment]
Could you try the command: ip ssh keygen

Found a topic buth it's Russians
https://help.keenetic.com/hc/ru/articles/360000387189-%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-SSH-%D0%BA-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%BE%D0%B9-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B5-Keenetic

**Comment by allmoney** [comment]
![image](https://user-images.githubusercontent.com/939594/80920128-7366dd80-8d76-11ea-8704-ca0a6cc9bb43.png)

Support said that I can try to install OPKG Entware and use full support of dropbear.

**Comment by GeekVisit** [comment]
You need to be able to ssh into your router by command line. You'll  need to research how to do that for your particular router. And you'll need to be able to run tcpdump on the router via script. I don't have any information or insight on your particular router. Thanks to Tolleburker for helping out. I'm closing this.
