### ISSUE TITLE
Button press packet sequence changed?

### ISSUE THREAD

**Issue by macavelly** [GeekVisit/Simple-Skybell-Sniffer#2]
Hi,

First sorry it took me so long to thank you for this project. I have been using it over a year now and I have it where when the button press packet sequence is detected it sends a mqtt command to my raspi that then logs into my door camera vis rtsp and uploads a screenshot to imgur then sends the image to a google chat group. It all happens in 1-2 seconds. 

Its been working perfect for over a year now. However I don't know if they auto updated the firmware on the skybell trim plus but the old packet sequence for the button press doesn't happen anymore when the button is pressed.

The tcpdump command that has been working for me all this time is:

 tcpdump -lpntttti any host 192.168.107.70 and port 5683

Where 192.168.107.70 is the IP of my skybell. The 177,97,369 sequence repeats when idle and a 800+ packet still occurs when live viewing but the 97,49 or even the 465 packet never occurs anymore from button presses or motion detection. I've monitored the tcpdump when motion is detect and when the button is pressed and even thought the android app sends the alerts, the sequence never changes from 177,97,369

Current FW version for my SKYBELL_TRIMPLUS_1000030-F is 7082. I don't know if this is a new FW.

**Comment by thomasdelaet** [comment]
I have the same issue.

I get alternating 369,369,97 and 177,177,97 sequences with 30s in between. motion or pressing button does not change anything so I assume device is now communicating on another port?

I have SKYBELL_HD_4_0_1000010-F with firmware 5082. Will continue debugging ;-)

**Comment by thomasdelaet** [comment]
Notification seem to be done now over HTTPS by contacting cloud.myskybell.com

**Comment by macavelly** [comment]
did you every figure at way to detect the button press now that its over https?
I've been trying but no luck on my end.

**Comment by thomasdelaet** [comment]
I don't think that's possible ;-)

**Comment by macavelly** [comment]
I do believe you are correct. So, I decided to find work arounds. My first thought was to use IFTTT since skybell has an integration with IFTTT. A doorbell button push would trigger an IFTTT action but the delay was 10 minutes! what a joke.

But I wouldn't give up, I wanted back the function to get a picture almost instantly to my phone once the button is pushed. Long story short, I decide to use a reed switch on the indoor mechanical chime, hooked up to a sonoff basic GPIO pin which sends a MQTT message to my nodered. 

And voilà it works again!

Here are some video tutorials that anyone can follow in order to duplicate my setup. The vids aren't my exact set up but they give the general outlines. If anyone has specific question they can ask me. 

Would be interested to know what your work around if any you decided on @thomasdelaet 


https://www.youtube.com/watch?v=SuyuCwaFKwM
https://www.youtube.com/watch?v=qZqmkhpJ55A
https://www.youtube.com/watch?v=jL0Y6GoEdko

**Comment by thomasdelaet** [comment]
great workaround :-)

I will probably ditch the Skybell and go for https://magpi.raspberrypi.org/articles/smart-doorbell-and-video-intercom-system.

This would give me much more flexibility.

**Comment by GeekVisit** [comment]
Sorry for the delay in responding. I noticed this myself and have been troubleshooting. I think it's fixable. It's never depended on http - it's always assumed the packets are encrypted. That's why it's just looking at their size. They are using different ports now and the timing is a bit off.  I think I can fix it at least for my mikrotik setup.

**Comment by GeekVisit** [comment]
> 
> 
> Notification seem to be done now over HTTPS by contacting cloud.myskybell.com

The sniffer assumes encryption so this is not the reason why it stopped working. That's why the script looks at the packet size and doesn't attempt to read it. Read this: https://github.com/thoukydides/homebridge-skybell/wiki/Protocol-CoAP.   I believe it's just a matter of adjusting the script to detect the right timing.

**Comment by GeekVisit** [comment]
![2021-10-26_20-20-40-pattern-to-ring](https://user-images.githubusercontent.com/40548172/138983662-ee999e92-83fc-43a4-b184-758ac1a52e17.png)

Here's the pattern I see from using wireshark and the mikrotik sniffer. I've tweaked the perl script and it seems to be mostly working. I will update it. Essentially it's sending a DNS request to cloud.myskybell.com when the button is pushed and then does the same about 40 seconds later to download the video. It also does a cloud.mysql.com DNS lookup if you "drop in" so you have to distinguish that from the button push.

**Comment by GeekVisit** [comment]
After further testing this leads to unnecessary triggers and is unreliable. I'm deprecating this project as I have found a different way of triggering the automation- see the Readme.
