### ISSUE TITLE
1 из 1 skybell sniffer for opkg enabled router

### ISSUE THREAD

**Issue by shurakr** [GeekVisit/Simple-Skybell-Sniffer#3]
Hi,
I adapted your script to start the service for init.d
This allows it to run not only on ubuntu
I am attaching the files, see if it suits you, please publish it on your git page

Best regards,
Alex Krokhmal
[Skybell-opkg-initd.zip](https://github.com/GeekVisit/Simple-Skybell-Sniffer/files/7230187/Skybell-opkg-initd.zip)
`

**Comment by GeekVisit** [comment]
Thanks - this is interesting but I don't have a system to test this on so am not going to add it to the repository. You may want to make a fork and add it. Thank you.
