### ISSUE TITLE
 now the response from the service is 33 bytes instead of 49 as before

### ISSUE THREAD

**Issue by shurakr** [GeekVisit/Simple-Skybell-Sniffer#4]
if ((not $from_skybell and $length == 49)
      or ((not $from_skybell and $length == 33))

**Comment by GeekVisit** [comment]
I have added this though it's untested by me as I use tshark now.  I made the change in https://github.com/GeekVisit/Simple-Skybell-Sniffer/commit/710647203d78a3f142cadf18bb413c86308dac0e#diff-4b83781858202db593853df98631ebeb5cee311abc8d76a8132b1e04dfe0075c

Forgot that I had made the change so did not mention this issue in the commit  - sorry!
